In [2]:
x=[1,2,3,4]
x

[1, 2, 3, 4]

In [3]:
import numpy as np

In [4]:
np.__doc__

'\nNumPy\n=====\n\nProvides\n  1. An array object of arbitrary homogeneous items\n  2. Fast mathematical operations over arrays\n  3. Linear Algebra, Fourier Transforms, Random Number Generation\n\nHow to use the documentation\n----------------------------\nDocumentation is available in two forms: docstrings provided\nwith the code, and a loose standing reference guide, available from\n`the NumPy homepage <https://www.scipy.org>`_.\n\nWe recommend exploring the docstrings using\n`IPython <https://ipython.org>`_, an advanced Python shell with\nTAB-completion and introspection capabilities.  See below for further\ninstructions.\n\nThe docstring examples assume that `numpy` has been imported as `np`::\n\n  >>> import numpy as np\n\nCode snippets are indicated by three greater-than signs::\n\n  >>> x = 42\n  >>> x = x + 1\n\nUse the built-in ``help`` function to view a function\'s docstring::\n\n  >>> help(np.sort)\n  ... # doctest: +SKIP\n\nFor some objects, ``np.info(obj)`` may provide a

In [5]:
x=[3,4.0,34,'23']

In [6]:
x

[3, 4.0, 34, '23']

In [7]:
np.array(x)

array(['3', '4.0', '34', '23'], dtype='<U32')

In [8]:
np.array([2.,3.6],dtype='int')

array([2, 3])

In [9]:
np.array([2.,'3'],dtype='int')

array([2, 3])

In [10]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
x=np.zeros((2,3),dtype=int)

In [12]:
x[1][2]=10

In [13]:
x

array([[ 0,  0,  0],
       [ 0,  0, 10]])

In [14]:
x[1,1]=8

In [15]:
x

array([[ 0,  0,  0],
       [ 0,  8, 10]])

In [16]:
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [17]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [18]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [19]:
np.random.random((3,3))

array([[0.19492787, 0.10780158, 0.46188833],
       [0.43877066, 0.07258747, 0.32343815],
       [0.5890152 , 0.98713607, 0.06381689]])

In [20]:
np.random.normal(0,1,(3,3))

array([[-1.78253539,  0.33239601,  0.35285263],
       [-0.60850373, -0.2827938 , -0.80358526],
       [-0.80139551,  0.52226828, -2.2031569 ]])

In [21]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
np.random.seed(0)
x1=np.random.randint(10,size=6)
x2=np.random.randint(10,size=(3,4))

In [23]:
x1

array([5, 0, 3, 3, 7, 9])

In [24]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [25]:
x3=np.random.randint(10,size=(3,4,2))

In [26]:
x3

array([[[8, 1],
        [5, 9],
        [8, 9],
        [4, 3]],

       [[0, 3],
        [5, 0],
        [2, 3],
        [8, 1]],

       [[3, 3],
        [3, 7],
        [0, 1],
        [9, 9]]])

In [30]:
arr = np.arange(4)
arr.shape

(4,)

In [31]:
arr

array([0, 1, 2, 3])

In [32]:
row_vec = arr[np.newaxis, :]

In [33]:
row_vec.shape

(1, 4)

In [37]:
arr=[1,2,3,4]
y=np.array(arr)
y+100

array([101, 102, 103, 104])